export default class StorageKeys {
    static currentLangKey = "app.preference.currentLang"
    static layoutKey = "app.preference.layout"
    static themeKey = "app.preference.theme"
    static primaryColorKey = "app.preference.primaryColor"
    static colorWeakKey = "app.preference.colorWeak"
    static fixedHeaderKey = "app.preference.fixedHeader"
    static fixSiderbarKey = "app.preference.fixSiderbar"
    static contentWidthKey = "app.preference.contentWidth"
    static autoHideHeaderKey = "app.preference.autoHideHeader"
    static multiTabKey = "app.preference.multiTab"
    static autoLoginKey = "app.preference.autoLoginKey"
    static accountKey = "app.current.account"
    static registerBaseKey = "account.register.base.form"
}
